name: ci
on:
  - push
  - pull_request
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    continue-on-error: ${{ matrix.version == 'nightly' || matrix.version == 'pre'  }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.6'
          - '1'
          - 'pre'
          - 'nightly'
        os:
          - ubuntu-latest
          # - macOS-latest
          # - windows-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - name: Run Tests
        run: |
          julia --project=. -e 'using Pkg; Pkg.build()' || exit_code_build=$? || true
          julia --project=. -e 'using Pkg; Pkg.test()' || exit_code_test=$? || true
          if [ "${exit_code_build:-0}" -ne 0 ] || [ "${exit_code_test:-0}" -ne 0 ]; then
            if [[ "${{ matrix.version }}" == "nightly" || "${{ matrix.version }}" == "pre" ]]; then
              echo "::warning::Optional matrix job failed for ${{ matrix.version }}."
              exit 0  # Ignore failure for optional jobs
            else
              echo "Build or test failed"
              exit 1  # Fail for stable versions
            fi
          fi
